-- Replaces the flat survey_answers model with a normalized one:
--   - questions / answer_options: enum-style lookup tables giving
--     survey_answers real FK integrity instead of a free-text question_id.
--     Not read by the app at runtime (rendering still comes from
--     src/config/surveyQuestions.ts) — these exist purely so a written
--     answer is guaranteed to reference a real question/option, and for
--     readability when inspecting the data directly.
--   - survey_answers: one row per submission+question for single/text
--     questions, one row per submission+question+option for multi-select
--     questions (one row per selected option). Deselecting/clearing an
--     answer sets is_selected = false rather than deleting the row, since
--     anon has no DELETE policy (see 0002_rls_policies.sql) and we're not
--     adding one.
--
-- No production data exists yet (only in-progress draft rows from local
-- testing), so this drops and recreates rather than migrating in place.

drop table if exists survey_answers;
drop table if exists survey_submissions;
drop table if exists answer_options;
drop table if exists questions;

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------
-- Lookup tables (enum-style).
-- ---------------------------------------------------------------------

create table questions (
    id         varchar(50) primary key,  -- matches SURVEY_QUESTIONS[].id in src/config/surveyQuestions.ts
    prompt     text not null,
    type       varchar(20) not null check (type in ('single', 'multiple', 'text', 'textarea')),
    section    varchar(20) check (section in ('core', 'demographic')),
    required   boolean not null default false,
    sort_order int not null,
    created_at timestamptz not null default now()
);

create table answer_options (
    question_id varchar(50) not null references questions(id) on delete cascade,
    value       varchar(50) not null,
    label       text not null,
    sort_order  int not null,
    primary key (question_id, value)
);

-- ---------------------------------------------------------------------
-- Submissions (unchanged shape from the previous schema).
-- ---------------------------------------------------------------------

create table survey_submissions (
    id uuid primary key,  -- generated by the app, not gen_random_uuid() — see src/lib/db/submissions.ts
    survey_version varchar(20) not null default 'v1',
    source varchar(50),
    started_at timestamptz,
    completed_at timestamptz,
    area varchar(100),
    age_group varchar(50),
    purchase_frequency varchar(100),

    -- Denormalized mirrors of Q1/Q2 answers, for fast dashboard aggregation.
    -- survey_answers remains the source of truth for these questions.
    purchase_channel varchar(50),
    store_name text,
    store_area text,
    online_platform text,

    created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Answers.
-- ---------------------------------------------------------------------

create table survey_answers (
    id uuid primary key default gen_random_uuid(),
    submission_id uuid not null references survey_submissions(id) on delete cascade,
    question_id varchar(50) not null references questions(id),
    option_id varchar(50),  -- references answer_options.value for this question; null for free-text answers
    answer_text text,       -- free-text answers, or the "please specify" text alongside option_id = 'other'
    is_selected boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    foreign key (question_id, option_id) references answer_options (question_id, value)
    -- (a multi-column FK is skipped by Postgres when any column is null, so
    -- free-text rows with option_id = null bypass this check naturally)
);

create index idx_survey_submissions_created_at on survey_submissions (created_at desc);
create index idx_survey_submissions_area on survey_submissions (area);
create index idx_survey_submissions_purchase_channel on survey_submissions (purchase_channel);
create index idx_survey_answers_submission_id on survey_answers (submission_id);
create index idx_survey_answers_question_id on survey_answers (question_id, option_id);

-- ---------------------------------------------------------------------
-- RLS — same trust model as before: anon writes blind (insert/update,
-- never select/delete), authenticated (admin) reads everything.
-- ---------------------------------------------------------------------

alter table questions enable row level security;
alter table answer_options enable row level security;
alter table survey_submissions enable row level security;
alter table survey_answers enable row level security;

create policy "authenticated can select questions"
    on questions for select to authenticated using (auth.role() = 'authenticated');
create policy "authenticated can select answer_options"
    on answer_options for select to authenticated using (auth.role() = 'authenticated');

create policy "anon can insert survey_submissions"
    on survey_submissions for insert to anon with check (true);
create policy "anon can update survey_submissions"
    on survey_submissions for update to anon using (true) with check (true);
create policy "authenticated can select survey_submissions"
    on survey_submissions for select to authenticated using (auth.role() = 'authenticated');

create policy "anon can insert survey_answers"
    on survey_answers for insert to anon with check (true);
create policy "anon can update survey_answers"
    on survey_answers for update to anon using (true) with check (true);
create policy "authenticated can select survey_answers"
    on survey_answers for select to authenticated using (auth.role() = 'authenticated');

-- ---------------------------------------------------------------------
-- Seed data — mirrors src/config/surveyQuestions.ts exactly, in the same
-- order. If that file changes, this seed needs a matching migration.
-- ---------------------------------------------------------------------

insert into questions (id, prompt, type, section, required, sort_order) values
  ('q1_purchase_channel', 'Where do you usually buy dry fruits?', 'single', 'core', true, 1),
  ('q2_store_name', 'If you buy offline, which shop/store do you usually buy from?', 'text', 'core', false, 2),
  ('q2_store_area', 'Which area is the store located in?', 'text', 'core', false, 3),
  ('q2_online_platform', 'Which website/app do you usually buy from?', 'text', 'core', false, 4),
  ('q3_purchase_reasons', 'What are the main reasons you choose this shop/website?', 'multiple', 'core', false, 5),
  ('primary_factor', 'Overall, what matters MOST to you when buying dry fruits?', 'single', 'core', false, 6),
  ('q4_likes_most', 'What do you like MOST about your current place to buy dry fruits?', 'textarea', 'core', false, 7),
  ('q5_dislikes', 'What do you NOT like about your current dry-fruit shopping experience?', 'multiple', 'core', false, 8),
  ('improvement_priority', 'If your current shop/website improved on any of these, would it make a real difference?', 'multiple', 'core', false, 9),
  ('q6_change_one_thing', 'If you could change ONE thing about your current dry-fruit shop/website, what would you change?', 'textarea', 'core', false, 10),
  ('favorite_dry_fruits', 'Which dry fruits do you buy most often?', 'multiple', 'core', false, 11),
  ('pack_size_preference', 'What pack size do you usually prefer?', 'single', 'core', false, 12),
  ('monthly_budget', 'What''s your monthly budget for dry fruits?', 'single', 'core', false, 13),
  ('quick_delivery_interest', 'Would you like good-quality dry fruits delivered to your home in 10 minutes?', 'single', 'core', false, 14),
  ('subscription_interest', 'Would a monthly dry-fruit subscription (auto-delivered on a schedule, no need to reorder) interest you?', 'single', 'core', false, 15),
  ('q11_switch_reasons', 'What would make you try a NEW dry-fruit store instead of your current shop?', 'multiple', 'core', false, 16),
  ('q12_owner_suggestion', 'One final question — you are the owner now!', 'textarea', 'core', false, 17),
  ('area', 'Which area are you in?', 'single', 'demographic', false, 18),
  ('age_group', 'Which age group do you belong to?', 'single', 'demographic', false, 19),
  ('purchase_frequency', 'How often do you buy dry fruits?', 'single', 'demographic', false, 20);

insert into answer_options (question_id, value, label, sort_order) values
  ('q1_purchase_channel', 'local_shop', 'Local dry-fruit shop', 1),
  ('q1_purchase_channel', 'supermarket', 'Supermarket', 2),
  ('q1_purchase_channel', 'online', 'Online website/app', 3),
  ('q1_purchase_channel', 'whatsapp_instagram', 'WhatsApp/Instagram seller', 4),
  ('q1_purchase_channel', 'wholesale_market', 'Wholesale market', 5),
  ('q1_purchase_channel', 'dont_buy', 'I don''t usually buy dry fruits', 6),
  ('q1_purchase_channel', 'other', 'Other', 7),

  ('q3_purchase_reasons', 'price', 'Price', 1),
  ('q3_purchase_reasons', 'product_quality', 'Product quality', 2),
  ('q3_purchase_reasons', 'freshness', 'Freshness', 3),
  ('q3_purchase_reasons', 'trust', 'Trust', 4),
  ('q3_purchase_reasons', 'location_convenience', 'Location/convenience', 5),
  ('q3_purchase_reasons', 'variety', 'Variety', 6),
  ('q3_purchase_reasons', 'offers_discounts', 'Offers/discounts', 7),
  ('q3_purchase_reasons', 'packaging', 'Packaging', 8),
  ('q3_purchase_reasons', 'easy_online_ordering', 'Easy online ordering', 9),
  ('q3_purchase_reasons', 'fast_delivery', 'Fast delivery', 10),
  ('q3_purchase_reasons', 'customer_service', 'Customer service', 11),
  ('q3_purchase_reasons', 'family_tradition', 'Family has been buying there for a long time', 12),
  ('q3_purchase_reasons', 'other', 'Other', 13),

  ('primary_factor', 'quality', 'Quality', 1),
  ('primary_factor', 'quantity_pack_options', 'Quantity/pack size options', 2),
  ('primary_factor', 'price', 'Price', 3),
  ('primary_factor', 'customer_experience', 'Customer experience/service', 4),
  ('primary_factor', 'shop_ambience', 'Shop cleanliness & ambience', 5),
  ('primary_factor', 'freshness', 'Freshness', 6),
  ('primary_factor', 'variety', 'Variety', 7),
  ('primary_factor', 'trust_brand', 'Trust/brand reputation', 8),
  ('primary_factor', 'other', 'Other', 9),

  ('q5_dislikes', 'price_high', 'Price is high', 1),
  ('q5_dislikes', 'quality_inconsistent', 'Quality is not always consistent', 2),
  ('q5_dislikes', 'not_fresh', 'Products are sometimes not fresh', 3),
  ('q5_dislikes', 'not_enough_variety', 'Not enough variety', 4),
  ('q5_dislikes', 'hard_to_compare', 'Difficult to compare products', 5),
  ('q5_dislikes', 'packaging_could_be_better', 'Packaging could be better', 6),
  ('q5_dislikes', 'no_small_quantity', 'No small quantity options', 7),
  ('q5_dislikes', 'no_customisation', 'No customisation', 8),
  ('q5_dislikes', 'delivery_slow', 'Delivery takes too long', 9),
  ('q5_dislikes', 'delivery_charges_high', 'Delivery charges are high', 10),
  ('q5_dislikes', 'shop_too_far', 'Shop is too far', 11),
  ('q5_dislikes', 'customer_service_could_be_better', 'Customer service could be better', 12),
  ('q5_dislikes', 'unsure_about_quality', 'I don''t know whether the quality is really good', 13),
  ('q5_dislikes', 'nothing_happy', 'Nothing — I''m happy with my current experience', 14),
  ('q5_dislikes', 'other', 'Other', 15),

  ('improvement_priority', 'quality', 'Quality', 1),
  ('improvement_priority', 'quantity_pack_options', 'Quantity/pack size options', 2),
  ('improvement_priority', 'customer_experience', 'Customer experience/service', 3),
  ('improvement_priority', 'price', 'Price', 4),
  ('improvement_priority', 'shop_ambience', 'Shop cleanliness & ambience', 5),
  ('improvement_priority', 'freshness', 'Freshness', 6),
  ('improvement_priority', 'variety', 'Variety', 7),
  ('improvement_priority', 'packaging', 'Packaging', 8),
  ('improvement_priority', 'delivery_speed', 'Delivery speed/convenience', 9),
  ('improvement_priority', 'other', 'Other', 10),

  ('favorite_dry_fruits', 'almonds', 'Almonds', 1),
  ('favorite_dry_fruits', 'cashews', 'Cashews', 2),
  ('favorite_dry_fruits', 'pistachios', 'Pistachios', 3),
  ('favorite_dry_fruits', 'walnuts', 'Walnuts', 4),
  ('favorite_dry_fruits', 'dates', 'Dates', 5),
  ('favorite_dry_fruits', 'raisins', 'Raisins', 6),
  ('favorite_dry_fruits', 'figs', 'Figs (anjeer)', 7),
  ('favorite_dry_fruits', 'mixed_dry_fruit_packs', 'Mixed dry-fruit packs', 8),
  ('favorite_dry_fruits', 'dry_fruit_powder_mix', 'Dry-fruit powder/health mix', 9),
  ('favorite_dry_fruits', 'other', 'Other', 10),

  ('pack_size_preference', '100g_trial', '100g (trial size)', 1),
  ('pack_size_preference', '250g', '250g', 2),
  ('pack_size_preference', '500g', '500g', 3),
  ('pack_size_preference', '1kg', '1kg', 4),
  ('pack_size_preference', '1kg_plus_bulk', '1kg+ (bulk)', 5),
  ('pack_size_preference', 'depends_on_product', 'Depends on the dry fruit', 6),

  ('monthly_budget', 'under_500', 'Under ₹500', 1),
  ('monthly_budget', '500_1000', '₹500 – ₹1,000', 2),
  ('monthly_budget', '1000_2000', '₹1,000 – ₹2,000', 3),
  ('monthly_budget', '2000_5000', '₹2,000 – ₹5,000', 4),
  ('monthly_budget', 'above_5000', 'Above ₹5,000', 5),
  ('monthly_budget', 'only_during_festivals_occasions', 'Only during festivals/special occasions', 6),

  ('quick_delivery_interest', 'yes_definitely', 'Yes, definitely', 1),
  ('quick_delivery_interest', 'yes_if_quality_is_trustworthy', 'Yes, if I can trust the quality', 2),
  ('quick_delivery_interest', 'maybe_depends_on_price', 'Maybe, depends on price', 3),
  ('quick_delivery_interest', 'no_prefer_buying_in_person', 'No, I prefer buying in person', 4),
  ('quick_delivery_interest', 'no_prefer_planned_bulk_orders', 'No, I prefer planned/bulk orders', 5),

  ('subscription_interest', 'yes', 'Yes', 1),
  ('subscription_interest', 'maybe', 'Maybe', 2),
  ('subscription_interest', 'no', 'No', 3),

  ('q11_switch_reasons', 'better_price', 'Better price', 1),
  ('q11_switch_reasons', 'better_quality', 'Better quality', 2),
  ('q11_switch_reasons', 'fresher_products', 'Fresher products', 3),
  ('q11_switch_reasons', 'more_variety', 'More variety', 4),
  ('q11_switch_reasons', 'better_packaging', 'Better packaging', 5),
  ('q11_switch_reasons', 'home_delivery', 'Home delivery', 6),
  ('q11_switch_reasons', 'faster_delivery', 'Faster delivery (e.g. 10-minute delivery)', 7),
  ('q11_switch_reasons', 'easy_whatsapp_ordering', 'Easy WhatsApp ordering', 8),
  ('q11_switch_reasons', 'easy_website_ordering', 'Easy website ordering', 9),
  ('q11_switch_reasons', 'better_customer_service', 'Better customer service', 10),
  ('q11_switch_reasons', 'loyalty_rewards', 'Loyalty/rewards', 11),
  ('q11_switch_reasons', 'attractive_offers', 'Attractive offers', 12),
  ('q11_switch_reasons', 'something_different', 'Something completely different', 13),
  ('q11_switch_reasons', 'would_not_switch', 'I would not switch', 14),

  ('area', 'Pattabiram', 'Pattabiram', 1),
  ('area', 'Avadi', 'Avadi', 2),
  ('area', 'Nemilicheri', 'Nemilicheri', 3),
  ('area', 'Veppampattu', 'Veppampattu', 4),
  ('area', 'Thiruninravur', 'Thiruninravur', 5),
  ('area', 'Tiruvallur', 'Tiruvallur', 6),
  ('area', 'Chennai', 'Chennai', 7),
  ('area', 'Other', 'Other', 8),

  ('age_group', 'under_18', 'Under 18', 1),
  ('age_group', '18_24', '18–24', 2),
  ('age_group', '25_34', '25–34', 3),
  ('age_group', '35_44', '35–44', 4),
  ('age_group', '45_54', '45–54', 5),
  ('age_group', '55_plus', '55+', 6),

  ('purchase_frequency', 'every_week', 'Every week', 1),
  ('purchase_frequency', '2_3_times_a_month', '2–3 times a month', 2),
  ('purchase_frequency', 'once_a_month', 'Once a month', 3),
  ('purchase_frequency', 'every_few_months', 'Every few months', 4),
  ('purchase_frequency', 'mainly_festivals_functions', 'Mainly during festivals/functions', 5),
  ('purchase_frequency', 'rarely', 'Rarely', 6);
